In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [16]:
path = "../../data/telecomunicatii.csv"

df= pd.read_csv(path)
df.head()

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,payment_delay
0,HI,33,area_code_415,no,no,0,200.5,117,34.09,159.9,111,13.59,196.2,84,8.83,16.3,6,4.40,3,no
1,TN,80,area_code_415,yes,no,0,276.5,122,47.01,195.6,79,16.63,210.3,78,9.46,7.2,3,1.94,1,yes
2,CT,37,area_code_408,no,no,0,134.9,98,22.93,248.4,130,21.11,236.2,113,10.63,14.7,2,3.97,3,no
3,TN,106,area_code_415,no,no,0,119.2,142,20.26,228.4,139,19.41,197.9,61,8.91,8.4,9,2.27,2,no
4,TX,123,area_code_408,no,no,0,260.9,85,44.35,168.5,103,14.32,178.3,91,8.02,13.3,5,3.59,3,no

In [22]:
print(df['area_code'].unique())

<StringArray>
['area_code_415', 'area_code_408', 'area_code_510']
Length: 3, dtype: str

In [17]:
print(df.isnull().sum())

state                            0
account_length                   0
area_code                        0
international_plan               0
voice_mail_plan                  0
number_vmail_messages            0
total_day_minutes                0
total_day_calls                  0
total_day_charge                 0
total_eve_minutes                0
total_eve_calls                  0
total_eve_charge                 0
total_night_minutes              0
total_night_calls                0
total_night_charge               0
total_intl_minutes               0
total_intl_calls                 0
total_intl_charge                0
number_customer_service_calls    0
payment_delay                    0
dtype: int64

In [18]:
X = df.drop(columns=['payment_delay']) 
y = df['payment_delay']

In [31]:
le = LabelEncoder()
y =le.fit_transform(y)

categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
print(categorical_cols)
numeric_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
print(numeric_cols)

['state', 'area_code', 'international_plan', 'voice_mail_plan']
['account_length', 'number_vmail_messages', 'total_day_minutes', 'total_day_calls', 'total_day_charge', 'total_eve_minutes', 'total_eve_calls', 'total_eve_charge', 'total_night_minutes', 'total_night_calls', 'total_night_charge', 'total_intl_minutes', 'total_intl_calls', 'total_intl_charge', 'number_customer_service_calls']

/tmp/ipykernel_10655/830569769.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include=['object']).columns.tolist()

In [29]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(drop='first', sparse_output=False), categorical_cols)
    ],
    remainder='passthrough' # keep numerical col 
)

X_processed = preprocessor.fit_transform(X)

encoded_cols = preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols)
all_features = list(encoded_cols) + numeric_cols

X_df = pd.DataFrame(X_processed, columns=all_features)

In [30]:
X_df

,state_AL,state_AR,state_AZ,state_CA,state_CO,state_CT,state_DC,state_DE,state_FL,state_GA,...,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,159.9,111.0,13.59,196.2,84.0,8.83,16.3,6.0,4.40,3.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,195.6,79.0,16.63,210.3,78.0,9.46,7.2,3.0,1.94,1.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,248.4,130.0,21.11,236.2,113.0,10.63,14.7,2.0,3.97,3.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,228.4,139.0,19.41,197.9,61.0,8.91,8.4,9.0,2.27,2.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,168.5,103.0,14.32,178.3,91.0,8.02,13.3,5.0,3.59,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,214.8,77.0,18.26,206.4,73.0,9.29,8.7,6.0,2.35,2.0
2996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,251.3,116.0,21.36,200.1,112.0,9.00,8.4,2.0,2.27,5.0
2997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,181.6,79.0,15.44,155.6,104.0,7.00,8.3,6.0,2.24,3.0
2998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,114.7,116.0,9.75,104.7,83.0,4.71,13.2,5.0,3.56,1.0
2999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,108.5,118.0,9.22,232.0,72.0,10.44,10.6,3.0,2.86,2.0

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X_df, y, test_size=0.2, random_state=42, stratify=y)

print(X_train.shape)
print(X_test.shape)

(2400, 69)
(600, 69)

In [34]:
scaler = StandardScaler()

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [35]:
X_train

,state_AL,state_AR,state_AZ,state_CA,state_CO,state_CT,state_DC,state_DE,state_FL,state_GA,...,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls
672,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.766454,0.701466,1.766417,1.258403,0.627038,1.258347,0.113220,-0.194428,0.119229,-1.219188
1001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.937153,1.461497,1.936526,-0.138048,0.880866,-0.139606,0.797672,-0.603751,0.799772,-0.452805
2899,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,-2.707859,0.802803,-2.708400,-1.109915,-0.388271,-1.109084,0.257315,-0.194428,0.252668,-0.452805
2368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.775952,0.296116,-0.775771,0.461822,0.525507,0.461990,0.545506,0.214894,0.546236,-0.452805
616,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.432996,-0.869264,0.433895,-1.557870,0.576273,-1.559199,1.806339,-0.194428,1.800571,-0.452805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2051,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.730306,-1.223945,1.730977,1.098697,1.642348,1.098210,-0.967495,1.033540,-0.961634,1.079961
1127,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.139796,-0.261239,0.140929,0.247583,-0.439037,0.245589,-0.355090,1.033540,-0.361155,-1.219188
615,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.181969,1.512165,0.181093,1.552495,1.083928,1.552653,0.401410,-1.422397,0.399452,0.313578
845,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.111231,-0.311908,-0.111872,-0.019243,-0.743630,-0.018421,0.401410,-0.603751,0.399452,-1.219188
1237,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.709774,0.042773,-1.709009,-0.459407,0.982397,-0.459880,-1.075566,0.624217,-1.081730,1.079961

In [36]:
y_train

array([1, 0, 0, ..., 1, 0, 0], shape=(2400,))

In [39]:
X_train_df = X_train.copy()
X_test_df = X_test.copy()

y_train_df = pd.DataFrame(y_train, columns=['Risk'])
y_test_df = pd.DataFrame(y_test, columns=['Risk'])

path = "/home/dana/partera_roz/data/preprocessed_data"
X_train_df.to_csv('/home/dana/partera_roz/data/preprocessed_data/X_train_df.csv', index=False)
X_test_df.to_csv('/home/dana/partera_roz/data/preprocessed_data/X_test_df.csv', index=False)

y_train_df.to_csv('/home/dana/partera_roz/data/preprocessed_data/y_train_df.csv', index=False)
y_test_df.to_csv('/home/dana/partera_roz/data/preprocessed_data/y_test_df.csv', index=False)

In [40]:
import joblib
import os

# Creăm folderul pentru modele dacă nu există
os.makedirs('/home/dana/partera_roz/models', exist_ok=True)

# Salvăm obiectele
joblib.dump(preprocessor, '/home/dana/partera_roz/models/preprocessor.pkl')
joblib.dump(scaler, '/home/dana/partera_roz/models/scaler.pkl')

print("Toate artefactele au fost salvate cu succes în folderul /home/dana/partera_roz/models/'!")

Toate artefactele au fost salvate cu succes în folderul /home/dana/partera_roz/models/'!